version: '3'
services:
  flask:
    image: python3-image
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: main.py
      FLASK_ENV: development
    volumes:
      - ./ENGINE:/app
    command: flask run --host=0.0.0.0
  angular:
    image: angular-image
    ports:
      - "4200:4200"
    volumes:
      - ./UI/src:/app/src
      - ./UI/node_modules:/app/node_modules
    command: ng serve --host 0.0.0.0 --prod
 # db:
   # image: sqlite11-image
   # volumes:
    #  - ./DATABASE:/app
    #command: sqlite3 /forum.db